Config:
  Auto-Teleport-To-Lobby: true
  Time-To-Start: 2
  Min-Players-ToStart: 2
  Time-EndGame: 5
  Lobby-Scoreboard: true
  Maximum-Game-Time:
    Solo: 300
    Teams: 500
  Default-Language: ENGLISH
  Shuffle-Items-In-Chest: true
  Kits:
    Ender-Pearl-Perk-Give-Interval: 120
  Default-Refill-Time: 180
  Events:
    Solo:
      - REFILL&30
      - REFILL&67
    Teams:
      - REFILL&120
      - REFILL&260
  Coins:
    Per-Win: 10
    Per-Kill: 5
    Per-Death: -5
Version: 1
Debug-Mode: true