name: RealSkywars
version: ${project.version}
main: josegamerpt.realskywars.RealSkywars
api-version: 1.14
depend: [WorldEdit]
softdepend: [RealRegions, My_Worlds, Multiverse-Core, HolographicDisplays, PlaceholderAPI, DecentHolograms]
authors: [JoseGamer_PT]
description: Simple Skywars plugin coded on the 1.14 API
load: POSTWORLD