Version: 6
Debug-Mode: false
Config:
  Bungeecord:
    Enabled: false
    Kick-Player: true
    Lobby-Server: lobby
  Use-Vault-As-Currency: false
  Auto-Teleport-To-Lobby: true
  Scoreboard-In-Lobby: true
  Spectator-Shop: true
  Right-Click-Player-Info: true
  PlaceholderAPI-In-Scoreboard: false
  Disable-Player-Reset: false
  Disable-Language-Selection: false
  Disable-Map-Starting-Countdown:
    Message: false
    Actionbar: false
  Item-Slots:
    Lobby:
      Profile: 0
      Maps: 4
      Shop: 8
    Cage:
      Kit: 1
      Vote: 4
      Leave: 7
    Spectator:
      Spectate: 1
      Play-Again: 2
      Shop: 4
      Leave: 7
    Setup:
      Chest1: 0
      Cage: 4
      Chest2: 8
  # Time in seconds
  Time:
    Formatting: dd-MM-yyyy HH:mm:ss
    Offset: 0
  Time-To-Start: 10
  Min-Players-ToStart: 2
  Time-EndGame: 10
  Refresh-Leaderboards: 600
  Vote-Before-Seconds: 3
  Maximum-Game-Time:
    Solo: 300
    Teams: 500
  Shuffle-Items-In-Chest: true
  Kits:
    Ender-Pearl-Perk-Give-Interval: 120
  Default-Refill-Time: 180
  # Events: REFILL, TNTRAIN
  # REFILL refills the chests.
  # TNTRAIN, when executed, summons a TNT above all game players.
  # Event Config: <event>&<time of execution>
  Events:
    Solo:
      - REFILL&60
      - REFILL&120
    Teams:
      - REFILL&120
      - REFILL&260
  Coins:
    Per-Win: 10
    Per-Kill: 5
    Per-Death: -5
  Allowed-Commands:
    - sw
    - rsw
    - realskywars
  Random-Nicknames:
    - Strawberry
    - Dog
    - Cat
    - White
    - Black
    - Red
    - Green
    - Blue